name: CDK Deploy

on:
  push:
    branches:
      - main
      - '**'

env:
  AWS_DEFAULT_REGION: us-east-1

jobs:
  build-and-deploy:
    if: github.ref == 'refs/heads/main' || (github.ref != 'refs/heads/main' && !contains(github.event.head_commit.message, '[skip-ci]'))
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set environment for prod (main branch)
        run: echo "ENVIRONMENT=prod" >> $GITHUB_ENV
        if: github.ref == 'refs/heads/main'

      - name: Set environment for dev (other branches)
        run: echo "ENVIRONMENT=dev" >> $GITHUB_ENV
        if: github.ref != 'refs/heads/main'

      - name: Set PROJECT_URL
        run: echo "PROJECT_URL=https://github.com/${{ github.repository }}" >> $GITHUB_ENV

      - name: Set ROOT_DOMAIN
        run: echo "ROOT_DOMAIN=${{ secrets.ROOT_DOMAIN }}" >> $GITHUB_ENV

      - name: Set SUBDOMAIN
        run: echo "SUBDOMAIN=${{ secrets.SUBDOMAIN }}" >> $GITHUB_ENV

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}

      - name: Install AWS CDK CLI
        run: npm install -g aws-cdk

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Checkout private website repo
        run: |
          git clone https://x-access-token:${{ secrets.PRIVATE_REPO_TOKEN }}@github.com/${{ secrets.PRIVATE_REPO_OWNER }}/${{ secrets.PRIVATE_REPO_NAME }}.git website

      - name: Synthesize CDK
        run: cdk synth

      - name: Diff CDK Changes
        run: cdk diff

#      - name: Deploy CDK
#        run: cdk deploy --require-approval never --verbose
